### ISSUE TITLE
not python3 compatible

### ISSUE THREAD

**Issue by cooketho** [wutron/dlcpar#5]
Would it be possible to make your code Python3-compatible? Currently there are several print statements scattered throughout the code that are not compatible unless they are changed to print functions. So I get errors like this:

```
dlcpar
Traceback (most recent call last):
  File "./bin/dlcpar", line 11, in <module>
    from dlcpar import common
  File "/home/cooketho/lib/python2.7/site-packages/dlcpar/common.py", line 5, in <module>
    from rasmus import treelib, util
  File "/home/cooketho/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 1089
    print i, parentid
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(i, parentid)?
```

I can fix it by changing the following line in bin/dlcpar, but why not just make whole code compatible?

```
#!/usr/bin/env python
```
```
#!/usr/bin/env python2.7
```

**Comment by wutron** [comment]
Yes, I am planning on making the code Python 3-compatible.  Part of the problem is that I use some old libraries that also need to be updated.

So it is on my radar, but I probably will not get around to it until next summer at the earliest.  Apologies for the inconvenience.
